services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=teste
      - MYSQL_ROOT_PASSWORD=rafael
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=root

  gateways:
    image: matheusprotzen/gateways-mock
    container_name: gateways
    restart: always
    depends_on:
      - mysql
    ports:
      - "3001:3001"
      - "3002:3002"
